sudo: required
dist: trusty

# language: go

go:
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm

# install: go get -v github.com/spf13/hugo

before_script:
  - cd exampleSite
  - npm install mocha
  - npm install chai
  - npm install -g casperjs
  - npm install -g mocha-casperjs
  - npm install -g casper-chai

script:
  - bin/hugo version
  - bin/hugo
  - npm version
  - phantomjs --version; casperjs --version
