version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

install:
# Change the Path seperator to a Windows version (backslash)
- ps: >-
    $buildRoot = $ENV:APPVEYOR_BUILD_FOLDER

    $content = (Get-Content ($buildRoot + '\exampleSite\config.toml')) -join "`n"

    $content = $content -replace 'PathSeperator = "/"','PathSeperator = "\\"'

    Write-Output "config.toml content changed to:`n----`n$($content)"

    $content | Set-Content ($buildRoot + '\exampleSite\config.toml')

build_script:
#  Build the devopsdays-web site once
- ps: >-
    $buildRoot = $ENV:APPVEYOR_BUILD_FOLDER
    $buildRoot\bin\hugo version

test: off
